<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Feedback extends Model
{
    // The table name is singular 'feedback' as generated by the migration schema, or we can just specify it.
    // Laravel might assume 'feedbacks', so let's be explicit
    protected $table = 'feedback';

    protected $fillable = [
        'tahun_akademik',
        'responden',
        'nilai_kepuasan',
        'jumlah_responden',
        'keterangan',
    ];
}
